### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I had a look and the code and have these chage suggestions.

The biggest change is the removal of the deprecated dependency 'request'. The rest are little changes like formatting and typos.

No functional changes.

Thanks for this module! :slightly_smiling_face: 

BTW: With accepting this PR your module will be shown with keywords and a screenshot in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.

### CODE REVIEW

**Comment by mabahj** [comment]
Hi,
Thank you very much for reviewing and providing feedback! As you obviously have seen, I'm no js coder, I hacked together something that worked and left it at that. I had a look at your changes. From what I could see, they look good and probably make sense. One thing I noticed is that is _looks_ to me like it no longer includes the user agent? It is mandatory to fetch data from met.no.

**Comment by KristjanESPERANTO** [comment]
> As you obviously have seen, I'm no js coder, I hacked together something that worked and left it at that.

That's okay, you've built something that works :clap:. One great advantage of open source is that others can look at the code and suggest improvements :slightly_smiling_face: 

> One thing I noticed is that is looks to me like it no longer includes the user agent?
> It is mandatory to fetch data from met.no.

I tested it and it worked without it. But you are right, I just read it in the [Terms of Service](https://api.met.no/doc/TermsOfService): `"All requests must (if possible) include an identifying User Agent-string (UA) in the request ..."`. So I just re-entered the user agent into the code.

**Review by mabahj — COMMENTED** [review]
Thank you for helping!

**Comment by KristjanESPERANTO** [comment]
You're welcome! 🙂 The module looks great now in the new module list 🎉

**Pull request merged**
